### ISSUE TITLE
grabix hangs on non-bgzipped file

### ISSUE THREAD

**Issue by brentp** [arq5x/grabix#17]
example

``` Shell
echo asdf | gzip -c > t.gz
grabix index t.gz
```

**Comment by arq5x** [comment]
Nice catch, should be a simple fix.

**Comment by chapmanb** [comment]
Aaron and Brent;
We also see this hanging behavior on bgzip files produced by bcl2fastq and as a result need to always re-bgzip inputs since we can't tell if they're prepared correctly. Here is a test case that demonstrates the issue:
```
wget https://s3.amazonaws.com/chapmanb/testcases/grabix-bcl2fastq-hang.fq.gz
gunzip -c grabix-bcl2fastq-hang.fq.gz | bgzip -c > grabix-bcl2fastq-fix.fq.gz
time grabix index grabix-bcl2fastq-fix.fq.gz
time grabix index grabix-bcl2fastq-hang.fq.gz
```
The re-bgzipped input will index in a few seconds but the original (which comes straight out of illumina output) hangs indefinitely. `grabix check`, and thus htslib, thinks both are bgzipped and I haven't been able to figure out what is different about the illumina output that causes it to behave badly.

It would be useful if we could either avoid the hang, or programmatically detect what is wrong with the original bgzipped input so we know to always re-bgzip it. Thanks so much for looking at this and let me know if there is any other information I can provide.

**Comment by brentp** [comment]
thanks for the test-case.
I opened a PR to fix this. @arq5x can you merge? I don't have perms on this repo.

**Comment by chapmanb** [comment]
Brent;
Thanks so much for looking at this. I prepared a bioconda package with your fix by adding the patch to 0.1.7 but it still hangs for me on the test case I posted above. If you install the bioconda package can you reproduce the hang as well? Did I do anything wrong in prepping that or am I missing anything else? Thanks again.

**Comment by brentp** [comment]
sorry, I commented out a critical `break` I pushed another commit to the PR that fixes your test-case.

**Comment by chapmanb** [comment]
Brent -- brilliant, thank you. The new version does work cleanly for me, thanks for the quick fix to the fix. I'll get the bioconda package updated with the updated patch. Thanks again.
